### ISSUE TITLE
Generated address is invalid for BitFinex !

### ISSUE THREAD

**Issue by Ulawun** [arancauchi/IOTA-Paper-Wallet#9]
Hi,
I generated a paper wallet.
I tried to transfer IOTA from BitFinex to the wallet.
I got the error from BitFinex: "Invalid IOTA address" !
Does anybody know,
how to generate a paper wallet,
which works with BitFinex ?
Thanks.

**Comment by seabirdsea** [comment]
I thought when putting your seed into the wallet gen it would give a error if the seed was not correct?

**Comment by Ulawun** [comment]
The wallet gen didn't give my an error.
So I think my seed was correct.

**Comment by seabirdsea** [comment]
did you copy and past your receiving address onto bitfinex or type it in?

**Comment by Ulawun** [comment]
Yes, I copied and pasted my receiving address (wallet address) onto bitfinex withdrawal.

**Comment by arancauchi** [comment]
Hi Ulawun. What I think may be the problem is that my seed generator generates an address with a checksum at the end of the address. For example, this address I generated here contains 90 chars:
ZCYYKDXLVGMNGSQAKKNAXTRMHXEDYSBFQCPTZXUXVFUEXFPCNVDCLOJYWIEJIAE9ZUFQYNQRYG9XNJIZA**YAYU9PAG**
The final 9 chars are used as a sort of validator to ensure that the address is correctly formed. What bitfinex must be doing is not allowing addresses with checksums. Try inputting an address without the last 9 chars of your address and see what happens :)
